language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t liormb/client-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run liormb/client-tests npm test -- --coverage

after_success:
  - docker build -t liormb/multi-client ./client
  - docker build -t liormb/multi-nginx ./nginx
  - docker build -t liormb/multi-server ./server
  - docker build -t liormb/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to docker hub
  - docker push liormb/multi-client
  - docker push liormb/multi-nginx
  - docker push liormb/multi-server
  - docker push liormb/multi-worker
